### PR TITLE
Added BMI calculator

### PR DESCRIPTION
**Pull request by pavithra-064**
Added BMI calculator using vue js

Fixes #issue_number_here 
#205 issue number

 
# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] Project must follow good coding practices.
- [x] Project must be related to web development only.
- [x] Project must be added to their respective category directory eg. `React/, Django/, Php/` etc.
- [x] It must have proper documentation (it would be better if it had demos or screenshots).
- [x] Avoid raising Spam PR's.

# Screenshots / Video:

image

image

image

### CODE REVIEW

**Comment by Aryamanz29** [comment]
Hey @pavithra-064, Could you please remove `package-lock.json` from your project?

**Comment by pavithra-064** [comment]
> Hey @pavithra-064, Could you please remove `package-lock.json` from your project?

Done :)

**Review by Aryamanz29 — APPROVED** [review]
LGTM, Thanks for contributing @pavithra-064 🥳

**Comment by pavithra-064** [comment]
> LGTM, Thanks for contributing @pavithra-064 🥳

Thank you so much 😊

**Pull request merged**
